// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/yaozhuangyanlingyu/kratos_study/activity/internal/biz"
	"github.com/yaozhuangyanlingyu/kratos_study/activity/internal/client"
	"github.com/yaozhuangyanlingyu/kratos_study/activity/internal/conf"
	"github.com/yaozhuangyanlingyu/kratos_study/activity/internal/registry"
	"github.com/yaozhuangyanlingyu/kratos_study/activity/internal/server"
	"github.com/yaozhuangyanlingyu/kratos_study/activity/internal/service"

	"github.com/go-kratos/kratos/v2"
	"github.com/go-kratos/kratos/v2/log"
)

// Injectors from wire.go:

// wireApp init kratos application.
func wireApp(confServer *conf.Server, confRegistry *conf.Registry, confData *conf.Data, logger log.Logger) (*kratos.App, func(), error) {
	consulRegistry := registry.NewConsulRegistry(confRegistry)
	orderClient, err := client.NewOrderClient(consulRegistry, logger)
	if err != nil {
		return nil, nil, err
	}
	greeterUsecase := biz.NewActivityUsecase(logger, orderClient)
	greeterService := service.NewGreeterService(greeterUsecase)
	grpcServer := server.NewGRPCServer(confServer, greeterService, logger)
	httpServer := server.NewHTTPServer(confServer, greeterService, logger)
	app := newApp(logger, grpcServer, httpServer)
	return app, func() {}, nil
}
