server:
  http:
    addr: 0.0.0.0:701
    timeout: 1s
  grpc:
    addr: 0.0.0.0:702
    timeout: 1s
data:
  database:
    driver: mysql
    source: root:root@tcp(127.0.0.1:3306)/test
  redis:
    addr: 192.168.107.160:6379
    read_timeout: 0.2s
    write_timeout: 0.2s
    db: 0
    pool_size: 50
    min_idle_conns: 10
    max_retries: 3
